apiVersion: apps/v1
kind: Deployment
metadata:
  name: lists-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lists
  template:
    metadata:
      labels:
        app: lists
    spec:
      containers:
        - name: lists
          image: travisgerrard/lists
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://lists-mongo-srv:27017/lists'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: lists-srv
spec:
  selector:
    app: lists
  ports:
    - name: lists
      protocol: TCP
      port: 3000
      targetPort: 3000