apiVersion: apps/v1
kind: Deployment
metadata:
  name: meals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meals
  template:
    metadata:
      labels:
        app: meals
    spec:
      containers:
        - name: meals
          image: travisgerrard/meals
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://meals-mongo-srv:27017/meals'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: meals-srv
spec:
  selector:
    app: meals
  ports:
    - name: meals
      protocol: TCP
      port: 3000
      targetPort: 3000