name: deploy-payments

on: 
  push:
    branches:
      - main
    paths: 
      - 'payments/**'

jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd auth && docker build -t travisgerrard/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push travisgerrard/payments
