name: tests-ingredients

on:
  pull_request:
     paths:
       - 'ingredients/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ingredients && npm install && npm run test:ci
