name: tests-lists

on:
  pull_request:
     paths:
       - 'lists/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd lists && npm install && npm run test:ci
